version: "3.9"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_AUTH_DB: "admin"
      DB_HOST: "database"
      DB_PORT: 27017
      DB_NAME: "football"
      DB_USERNAME: "root"
      DB_PASSWORD: "supersecret"
      BATCH_PROCESS_ENDPOINT: "http://batch:3000/webhooks"
    depends_on:
      - batch
      - database
  batch:
    build: .
    environment:
      PORT: 3000
      FOOTBALL_DATA_API_TOKEN: ${FOOTBALL_DATA_API_TOKEN}
      DB_AUTH_DB: "admin"
      DB_HOST: "database"
      DB_PORT: 27017
      DB_NAME: "football"
      DB_USERNAME: "root"
      DB_PASSWORD: "supersecret"
    depends_on:
      - database
  database:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "supersecret"
