version: "3.9"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      FOOTBALL_DATA_API_TOKEN: ${FOOTBALL_DATA_API_TOKEN}
  database:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "supersecret"
